name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite disparar el deploy manualmente desde GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_SPACE_PATH: "urielmendez-edu/cotizador.onetrip"
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configurar identidad de Git para modificaciones locales de LFS
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Inicializar Git LFS
          git lfs install
          
          # Registrar las extensiones de archivos binarios en Git LFS
          git lfs track "*.ttf"
          git lfs track "*.jpg"
          git lfs track "*.jpeg"
          git lfs track "*.png"
          git lfs track "*.avif"
          
          # Agregar .gitattributes al commit
          git add .gitattributes
          
          # Hacer commit temporal de .gitattributes si fue creado o modificado
          git diff --cached --quiet || git commit -m "chore: configure Git LFS for binaries"
          
          # Agregar el remoto de Hugging Face y empujar de forma forzada
          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE_PATH
          git push hf main --force